### ISSUE TITLE
Update dont works with self hosted version

### ISSUE THREAD

**Issue by edinsof** [steveseguin/raspberry_ninja#13]
![wssmensajes](https://user-images.githubusercontent.com/3094013/136739003-16bd0efa-702d-4501-b0a9-fec393915e44.png)

You can view this stream at: https://vdo.ninja/?password=false&view=321
WSS CONNECTED
Traceback (most recent call last):
  File "publish.py", line 521, in <module>
    res = asyncio.get_event_loop().run_until_complete(c.loop())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "publish.py", line 352, in loop
    if msg['streamID'] == streamid:
NameError: name 'streamid' is not defined
root@raspberrypi:~/raspberry_ninja#

**Comment by steveseguin** [comment]
Thank you for that heads up. I haven't tested the self-hosted yet, but I'll get to that shortly. 

There's been a list of things needing testing; just got the raspberry pi code fixed, for example.

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/136741495-fde7dc21-8211-4428-9ac4-8e99a06cd967.png)

Working for me now.  Thank you for reporting the issue.


```python3 publish.py --streamid sdfasdfasdf --server wss://free3.piesocket.com/v3/1?api_key=OMXXXXXXXXXzNtfh6QKcDuspYK6RzvrZ5BhGyfGTsJkr3K0```
